---
- name: print hostname
  debug:
    msg: "hostname: {{ inventory_hostname }}"

- name: install required pkgs
  dnf:
    name: docker, jq
    state: present
  become: true

- template:
    src: etc_docker_daemon.json.j2
    dest: /etc/docker/daemon.json
  become: true

- name: restart service docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  become: true

- name: enable service docker
  systemd:
    name: docker
    enabled: yes
  become: true

- name: run docker postinstall step 1
  group:
    name: docker
    state: present
  become: true

- name: print ansible_user
  debug:
    msg: "ansible_user: {{ ansible_user }}"

- name: run docker postinstall step 2
  command: "usermod -aG docker {{ ansible_user }}"
  become: true


### docker login -u <kerberos>@redhat.com -p $(oc whoami -t) registry.reg-aws.openshift.com:443
### curl -L -O https://raw.githubusercontent.com/hongkailiu/svt-case-doc/master/scripts/check_images_cns_in_brew.sh
### bash -e ./check_images_cns_in_brew.sh
