apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: aaa-rc-yaml
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins
      openshift.io/deployment-config.name: jenkins
    name: jenkins-1
  spec:
    replicas: 1
    selector:
      app: jenkins
      deployment: jenkins-1
      deploymentconfig: jenkins
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: jenkins
          openshift.io/deployment.name: jenkins-1
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jenkins
          deployment: jenkins-1
          deploymentconfig: jenkins
      spec:
        containers:
        - image: docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: jenkins-volume-1
  status:
    replicas: 0
