kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "pvc-gluster"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
  
