#### oc process -f https://raw.githubusercontent.com/hongkailiu/svt-case-doc/master/files/template_test.yaml -p IMAGE=quay.io/hongkailiu/test-go:http-0.0.3 | oc create -f -
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: my-test-template
  annotations:
    template.openshift.io/bindable: "false"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: web
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: web
  spec:
    replicas: 1
    selector:
      name: web
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: web
      spec:
        containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: web
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    name: web
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: web
      weight: 100
    wildcardPolicy: None
parameters:
- description: Image
  displayName: Image
  name: IMAGE
  required: false
  value: docker.io/hongkailiu/svt-go:http
